// Mock data for prototype demonstration

export const mockAssets = [
  {
    id: '1',
    serialNumber: 'JN1234567890',
    hostname: 'mx240-core-01.oslo',
    assetTag: 'ASSET-001',
    model: {
      id: 'm1',
      modelName: 'MX240',
      modelType: 'ROUTER',
      manufacturer: 'Juniper Networks',
    },
    location: 'Oslo DC1, Rack A-12',
    rackPosition: 'U10-U12',
    status: 'ACTIVE',
    purchaseDate: '2022-03-15',
    purchasePrice: 45000,
    owner: 'Network Operations',
    licenses: [
      { id: 'l1', license: { softwareProduct: 'Junos OS Advanced', licenseType: 'SUBSCRIPTION' } },
    ],
    contracts: [
      { id: 'c1', contract: { contractNumber: 'JC-2024-001', contractType: 'PREMIUM_CARE' } },
    ],
    lastSyncAt: '2025-10-27T08:30:00Z',
    notes: 'Core router for Oslo datacenter',
  },
  {
    id: '2',
    serialNumber: 'JN0987654321',
    hostname: 'ex4300-access-02.oslo',
    assetTag: 'ASSET-002',
    model: {
      id: 'm2',
      modelName: 'EX4300-48T',
      modelType: 'SWITCH',
      manufacturer: 'Juniper Networks',
    },
    location: 'Oslo DC1, Rack B-05',
    rackPosition: 'U8',
    status: 'ACTIVE',
    purchaseDate: '2023-06-20',
    purchasePrice: 12000,
    owner: 'Network Operations',
    licenses: [],
    contracts: [
      { id: 'c2', contract: { contractNumber: 'JC-2024-001', contractType: 'PREMIUM_CARE' } },
    ],
    lastSyncAt: '2025-10-27T08:30:00Z',
  },
  {
    id: '3',
    serialNumber: 'JN1122334455',
    hostname: 'srx345-fw-01.bergen',
    assetTag: 'ASSET-003',
    model: {
      id: 'm3',
      modelName: 'SRX345',
      modelType: 'FIREWALL',
      manufacturer: 'Juniper Networks',
    },
    location: 'Bergen Office',
    rackPosition: 'U5',
    status: 'ACTIVE',
    purchaseDate: '2023-01-10',
    purchasePrice: 8500,
    owner: 'Security Team',
    licenses: [
      { id: 'l2', license: { softwareProduct: 'Juniper ATP Cloud', licenseType: 'SUBSCRIPTION' } },
    ],
    contracts: [],
    lastSyncAt: '2025-10-27T08:30:00Z',
    notes: 'Firewall for Bergen office - NO CONTRACT!',
  },
  {
    id: '4',
    serialNumber: 'JN5566778899',
    hostname: 'mx204-edge-01.trondheim',
    assetTag: 'ASSET-004',
    model: {
      id: 'm4',
      modelName: 'MX204',
      modelType: 'ROUTER',
      manufacturer: 'Juniper Networks',
    },
    location: 'Trondheim DC, Rack C-03',
    rackPosition: 'U15-U17',
    status: 'ACTIVE',
    purchaseDate: '2024-02-28',
    purchasePrice: 35000,
    owner: 'Network Operations',
    licenses: [],
    contracts: [
      { id: 'c3', contract: { contractNumber: 'JC-2024-002', contractType: 'JUNIPER_CARE' } },
    ],
    lastSyncAt: '2025-10-27T08:30:00Z',
  },
  {
    id: '5',
    serialNumber: 'JN9988776655',
    hostname: 'ex4300-spare-01',
    assetTag: 'ASSET-005',
    model: {
      id: 'm2',
      modelName: 'EX4300-48T',
      modelType: 'SWITCH',
      manufacturer: 'Juniper Networks',
    },
    location: 'Oslo DC1, Spare Parts',
    status: 'SPARE',
    purchaseDate: '2023-06-20',
    purchasePrice: 12000,
    owner: 'Network Operations',
    licenses: [],
    contracts: [],
    lastSyncAt: '2025-10-27T08:30:00Z',
  },
]

export const mockLicenses = [
  {
    id: 'l1',
    licenseKey: 'JUNOS-ADV-2024-ABC123',
    softwareProduct: 'Junos OS Advanced',
    licenseType: 'SUBSCRIPTION',
    quantity: 5,
    purchaseDate: '2024-01-15',
    expiryDate: '2025-01-15',
    cost: 15000,
    vendorContractNumber: 'JC-2024-001',
    isActive: true,
    assets: [
      { asset: { hostname: 'mx240-core-01.oslo', serialNumber: 'JN1234567890' } },
    ],
  },
  {
    id: 'l2',
    licenseKey: 'JATP-CLOUD-2024-XYZ789',
    softwareProduct: 'Juniper ATP Cloud',
    licenseType: 'SUBSCRIPTION',
    quantity: 10,
    purchaseDate: '2024-03-01',
    expiryDate: '2025-03-01',
    cost: 25000,
    vendorContractNumber: 'JC-2024-003',
    isActive: true,
    assets: [
      { asset: { hostname: 'srx345-fw-01.bergen', serialNumber: 'JN1122334455' } },
    ],
  },
  {
    id: 'l3',
    licenseKey: 'JUNOS-ENT-PERPETUAL-001',
    softwareProduct: 'Junos OS Enterprise',
    licenseType: 'PERPETUAL',
    quantity: 20,
    purchaseDate: '2022-06-10',
    expiryDate: null,
    cost: 45000,
    isActive: true,
    assets: [],
  },
  {
    id: 'l4',
    licenseKey: 'MIST-PREMIUM-2024-DEF456',
    softwareProduct: 'Mist Premium',
    licenseType: 'SUBSCRIPTION',
    quantity: 50,
    purchaseDate: '2024-04-01',
    expiryDate: '2025-04-01',
    cost: 12000,
    isActive: true,
    assets: [],
  },
]

export const mockContracts = [
  {
    id: 'c1',
    contractNumber: 'JC-2024-001',
    contractType: 'PREMIUM_CARE',
    vendor: 'Juniper Networks',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    renewalDate: '2024-11-01',
    annualCost: 125000,
    serviceLevel: '24x7, 4-hour response',
    autoRenewal: true,
    isActive: true,
    assets: [
      { asset: { hostname: 'mx240-core-01.oslo', model: { modelName: 'MX240' } } },
      { asset: { hostname: 'ex4300-access-02.oslo', model: { modelName: 'EX4300-48T' } } },
    ],
    notes: 'Premium support for critical infrastructure',
  },
  {
    id: 'c2',
    contractNumber: 'JC-2024-002',
    contractType: 'JUNIPER_CARE',
    vendor: 'Juniper Networks',
    startDate: '2024-03-01',
    endDate: '2025-02-28',
    annualCost: 45000,
    serviceLevel: 'Business hours, next-day response',
    autoRenewal: false,
    isActive: true,
    assets: [
      { asset: { hostname: 'mx204-edge-01.trondheim', model: { modelName: 'MX204' } } },
    ],
  },
  {
    id: 'c3',
    contractNumber: 'JC-2023-005',
    contractType: 'PREMIUM_CARE',
    vendor: 'Juniper Networks',
    startDate: '2023-01-01',
    endDate: '2023-12-31',
    annualCost: 95000,
    serviceLevel: '24x7, 4-hour response',
    autoRenewal: false,
    isActive: false,
    assets: [],
    notes: 'EXPIRED - needs renewal!',
  },
  {
    id: 'c4',
    contractNumber: 'JC-2024-003',
    contractType: 'PREMIUM_CARE',
    vendor: 'Juniper Networks',
    startDate: '2024-06-01',
    endDate: '2025-05-31',
    annualCost: 75000,
    serviceLevel: '24x7, 2-hour response',
    autoRenewal: true,
    isActive: true,
    assets: [],
  },
]

export const mockModels = [
  {
    id: 'm1',
    modelName: 'MX240',
    modelType: 'ROUTER',
    manufacturer: 'Juniper Networks',
    description: 'High-performance edge router',
    eolDate: null,
    eosDate: null,
    isActive: true,
    _count: { assets: 1 },
  },
  {
    id: 'm2',
    modelName: 'EX4300-48T',
    modelType: 'SWITCH',
    manufacturer: 'Juniper Networks',
    description: '48-port Gigabit Ethernet switch',
    eolDate: null,
    eosDate: null,
    isActive: true,
    _count: { assets: 2 },
  },
  {
    id: 'm3',
    modelName: 'SRX345',
    modelType: 'FIREWALL',
    manufacturer: 'Juniper Networks',
    description: 'Services Gateway for small to medium enterprises',
    eolDate: null,
    eosDate: null,
    isActive: true,
    _count: { assets: 1 },
  },
  {
    id: 'm4',
    modelName: 'MX204',
    modelType: 'ROUTER',
    manufacturer: 'Juniper Networks',
    description: 'Compact, low-power universal edge router',
    eolDate: null,
    eosDate: null,
    isActive: true,
    _count: { assets: 1 },
  },
  {
    id: 'm5',
    modelName: 'EX2300-C-12T',
    modelType: 'SWITCH',
    manufacturer: 'Juniper Networks',
    description: 'Compact 12-port switch',
    eolDate: '2028-12-31',
    eosDate: '2030-12-31',
    isActive: true,
    _count: { assets: 0 },
  },
]

export const mockDashboardStats = {
  totalAssets: 5,
  assetsWithoutContracts: 2,
  activeContracts: 3,
  expiringContracts: 1,
  totalLicenses: 4,
  totalAnnualCost: 245000,
}

export const mockAssetsByStatus = [
  { status: 'ACTIVE', count: 4 },
  { status: 'SPARE', count: 1 },
  { status: 'DEFECT', count: 0 },
  { status: 'RETIRED', count: 0 },
]

export const mockRecentSyncs = [
  {
    id: 's1',
    syncType: 'update',
    syncStatus: 'success',
    syncedAt: '2025-10-27T08:30:15Z',
    asset: { hostname: 'mx240-core-01.oslo', serialNumber: 'JN1234567890' },
  },
  {
    id: 's2',
    syncType: 'update',
    syncStatus: 'success',
    syncedAt: '2025-10-27T08:30:12Z',
    asset: { hostname: 'ex4300-access-02.oslo', serialNumber: 'JN0987654321' },
  },
  {
    id: 's3',
    syncType: 'create',
    syncStatus: 'success',
    syncedAt: '2025-10-27T08:30:08Z',
    asset: { hostname: 'mx204-edge-01.trondheim', serialNumber: 'JN5566778899' },
  },
]
